eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.server.com:8091/eureka/
  instance: 
    hostname: eureka.client.consumer2.com   
server:
  port: 8094
spring:
  application:
    name: service-consumer2